# Generated by Django 4.0.2 on 2022-03-01 15:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import libcloud.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AttachmentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=libcloud.models.get_content_upload_path)),
                ('creator', models.ForeignKey(on_delete=models.SET(libcloud.models.get_sentinel_user), to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('attachment_types', models.ManyToManyField(blank=True, to='libcloud.AttachmentType')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Library',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libcloud.contenttype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ContentTypeFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('type', models.IntegerField(choices=[(1, 'Number'), (2, 'String'), (3, 'Boolean')])),
                ('required', models.BooleanField(default=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libcloud.contenttype')),
            ],
        ),
        migrations.CreateModel(
            name='ContentFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=100)),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libcloud.content')),
                ('feature_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='libcloud.contenttypefeature')),
            ],
        ),
        migrations.AddField(
            model_name='content',
            name='library',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='libcloud.library'),
        ),
        migrations.AddField(
            model_name='content',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libcloud.contenttype'),
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=libcloud.models.get_attachment_upload_path)),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libcloud.content')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libcloud.attachmenttype')),
            ],
        ),
    ]
