# Generated by Django 4.0.2 on 2022-02-16 07:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import libcloud.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(choices=[(1, 'Video'), (2, 'Image'), (3, 'Book'), (4, 'Audio'), (5, 'Other')])),
                ('file', models.FileField(upload_to=libcloud.models.get_content_upload_path)),
                ('creator', models.ForeignKey(on_delete=models.SET(libcloud.models.get_sentinel_user), to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ContentFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('value', models.CharField(max_length=100)),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libcloud.content')),
            ],
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(choices=[(1, 'Subtitle'), (2, 'Other')])),
                ('file', models.FileField(upload_to=libcloud.models.get_attachment_upload_path)),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libcloud.content')),
            ],
        ),
    ]
