# Generated by Django 4.0.2 on 2022-02-16 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libcloud', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='type',
            field=models.IntegerField(choices=[(1, 'Video'), (2, 'Image'), (3, 'Text'), (4, 'Audio'), (5, 'Other')]),
        ),
    ]
