# Generated by Django 4.0.2 on 2022-02-20 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('libcloud', '0002_alter_attachment_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contentfeature',
            name='name',
        ),
        migrations.AddField(
            model_name='contentfeature',
            name='feature_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='libcloud.contenttypefeature'),
        ),
    ]
