# Generated by Django 4.0.2 on 2022-02-19 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libcloud', '0003_attachmenttype_contenttype_alter_content_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='type',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='content',
            name='type',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='contenttype',
            name='attachment_types',
            field=models.ManyToManyField(blank=True, to='libcloud.AttachmentType'),
        ),
    ]
