# Generated by Django 4.0.2 on 2022-02-18 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('libcloud', '0004_library_content_library'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libcloud.contenttype'),
        ),
    ]
